### ISSUE TITLE
Usage #!/usr/bin/env looks like a wrong way.

### ISSUE THREAD

**Issue by LazyKent** [jwilk/i18nspector#1]
Version 0.25.2.

From changelog:
`* Use /usr/bin/env in shebangs.`

As far as I can see, "/usr/bin/env interpreter_name" is deprecated by [Debian Python Policy](https://www.debian.org/doc/packaging-manuals/python-policy/ch-programs.html).
Also discussed in the [opensuse-packaging mailing list](http://lists.opensuse.org/opensuse-packaging/2016-08/msg00088.html).

**Comment by jwilk** [comment]
This is not a problem for Debian, as their Python packaging helper rewrites shebangs automatically.
Other distros that have the (quite sensible) policy of avoiding `/usr/bin/env` shebangs should probably do the same.

I don't want to hardcode path to the Python interpreter upstream, because `/usr/bin/python3` doesn't exist on some systems. At least on FreeBSD (and probably on other BSDs, too) `python3` lives in `/usr/local/bin/`.
(OTOH, `env` is in `/usr/bin` on all contemporary systems.)

That said, in 804598b22e0aa1864e205e6a261487aa0c56ab9c I made `make install` rewrite the shebang, which should fix the problem for you.
Let me know if you'd like to me make a new release (with this fix included) soon.

**Comment by LazyKent** [comment]
> I don't want to hardcode path to the Python interpreter upstream

I understand.

I'd like to package a new release before I go on vacation, on the 2nd of September.
Thanks.

**Comment by jwilk** [comment]
I've just released 0.25.3.
